// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  average_price: defineAsyncComponent(() => import("./Numbers/index.vue")),
  call_to_action: defineAsyncComponent(
    () => import("./CallToAction/index.vue"),
  ),
  faq: defineAsyncComponent(() => import("./Faq/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  images_carousel: defineAsyncComponent(() => import("./Carousel/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  test_slide: defineAsyncComponent(() => import("./LandingPageHero/index.vue")),
});
